using ICSP.Core.Constants;
using ICSP.Core.Logging;

namespace ICSP.Core.Manager.DeviceManager
{
  /// <summary>
  /// This message is generated by the master or device to confirm receipt of a message sent.
  /// The MessageID field must match the original message's MessageID and the Response bit should be set.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.Ack)]
  public class MsgCmdAck : ICSPMsg
  {
    public const int MsgCmd = DeviceManagerCmd.Ack;

    protected MsgCmdAck()
    {
    }

    public MsgCmdAck(byte[] buffer) : base(buffer)
    {
    }

    public override ICSPMsg FromData(byte[] bytes)
    {
      return new MsgCmdAck(bytes);
    }

    public static ICSPMsg CreateRequest(AmxDevice dest, AmxDevice source, ushort id)
    {
      var lRequest = new MsgCmdAck();
      
      return lRequest.Serialize(dest, source, id, MsgCmd, null);
    }

    public static ICSPMsg CreateRequest(ushort flag, AmxDevice dest, AmxDevice source, ushort id)
    {
      var lRequest = new MsgCmdAck();

      return lRequest.Serialize(flag, dest, source, id, MsgCmd, null);
    }

    public static ICSPMsg CreateRequest(ushort flag, AmxDevice dest, AmxDevice source, byte hop, ushort id)
    {
      var lRequest = new MsgCmdAck();

      return lRequest.Serialize(flag, dest, source, hop, id, MsgCmd, null);
    }

    protected override void WriteLogExtended()
    {
      Logger.LogDebug(false, "{0:l} ID: 0x{1:X4}", GetType().Name, ID);
    }
  }
}
