using ICSP.Core.Constants;

namespace ICSP.Core.Manager.DeviceManager
{
  /// <summary>
  /// The Request Output Channel Status message is generated by the master to
  /// request the status of a single Output Channel or status of all Output Channels.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.RequestOutputChannelStatus)]
  public class MsgCmdRequestOutputChannelStatus : MsgBaseCmdChannel<MsgCmdRequestOutputChannelStatus>
  {
    private MsgCmdRequestOutputChannelStatus()
    {
    }

    public MsgCmdRequestOutputChannelStatus(byte[] buffer) : base(buffer)
    {
    }

    public override ICSPMsg FromData(byte[] bytes)
    {
      return new MsgCmdRequestOutputChannelStatus(bytes);
    }

    protected override ushort MsgCmd
    {
      get
      {
        return DeviceManagerCmd.RequestOutputChannelStatus;
      }
    }
  }
}