using ICSP.Constants;

namespace ICSP.Manager.DeviceManager
{
  /// <summary>
  /// The Command message is generated by the master to communicate a command string.
  /// The format of a Command is similar to a “C Language” string, however, the semantics are different.
  /// A Command in a control system context is used to generate a “control” message. 
  /// This “control” message is generally intended to “command” the controlling device, 
  /// not the controlled device. 
  /// For example, a command to an RS232 port might enable XON/XOFF flow control. 
  /// This command affected the controlling device, but not the controlled device.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.CommandMasterDev)]
  public class MsgCmdCommandMasterDev : MsgBaseCmdText<MsgCmdCommandMasterDev>
  {
    private MsgCmdCommandMasterDev()
    {
    }

    public MsgCmdCommandMasterDev(byte[] buffer) : base(buffer)
    {
    }

    public override ICSPMsg FromData(byte[] bytes)
    {
      return new MsgCmdCommandMasterDev(bytes);
    }

    protected override ushort MsgCmd
    {
      get
      {
        return DeviceManagerCmd.CommandMasterDev;
      }
    }
  }
}
