using ICSP.Constants;

namespace ICSP.Manager.DeviceManager
{
  /// <summary>
  /// The Request Output Channel Status message is generated by the master to
  /// request the status of a single Output Channel or status of all Output Channels.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.RequestOutputChannelStatus)]
  public class MsgCmdRequestOutputChannelStatus : MsgBaseCmdChannel<MsgCmdRequestOutputChannelStatus>
  {
    private MsgCmdRequestOutputChannelStatus()
    {
    }

    public MsgCmdRequestOutputChannelStatus(ICSPMsgData msg) : base(msg)
    {
    }

    protected override ushort MsgCmd
    {
      get
      {
        return DeviceManagerCmd.RequestOutputChannelStatus;
      }
    }
  }
}