using ICSP.Constants;

namespace ICSP.Manager.DeviceManager
{
  /// <summary>
  /// The String message is generated by a device, sent to the master, to communicate a String.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.StringDevMaster)]
  public class MsgCmdStringDevMaster : MsgBaseCmdText<MsgCmdStringDevMaster>
  {
    private MsgCmdStringDevMaster()
    {
    }

    public MsgCmdStringDevMaster(byte[] buffer) : base(buffer)
    {
    }

    public override ICSPMsg FromData(byte[] bytes)
    {
      return new MsgCmdStringDevMaster(bytes);
    }

    protected override ushort MsgCmd
    {
      get
      {
        return DeviceManagerCmd.StringDevMaster;
      }
    }
  }
}