using ICSP.Constants;

namespace ICSP.Manager.DeviceManager
{
  /// <summary>
  /// The Command message is generated by a device, sent to the master, to communicate a Command string.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.CommandDevMaster)]
  public class MsgCmdCommandDevMaster : MsgBaseCmdText<MsgCmdCommandDevMaster>
  {
    private MsgCmdCommandDevMaster()
    {
    }

    public MsgCmdCommandDevMaster(byte[] buffer) : base(buffer)
    {
    }

    public override ICSPMsg FromData(byte[] bytes)
    {
      return new MsgCmdCommandDevMaster(bytes);
    }

    protected override ushort MsgCmd
    {
      get
      {
        return DeviceManagerCmd.CommandDevMaster;
      }
    }
  }
}