using ICSP.Constants;
using ICSP.Logging;

namespace ICSP.Manager.DeviceManager
{
  /// <summary>
  /// This message is generated by the master when the destination system/device for the message does not exist.
  /// This message indicates that a previous message was not routable by the master.
  /// The MessageID field must match the original message's MessageID and the Response bit should be set.
  /// </summary>
  [MsgCmd(DeviceManagerCmd.Nak)]
  public class MsgCmdNak : ICSPMsg
  {
    public const int MsgCmd = DeviceManagerCmd.Nak;

    protected MsgCmdNak()
    {
    }

    public MsgCmdNak(ICSPMsgData msg) : base(msg)
    {
    }

    public static ICSPMsg CreateRequest(AmxDevice dest, AmxDevice source, ushort id)
    {
      var lRequest = new MsgCmdNak();

      return lRequest.Serialize(dest, source, id, MsgCmd, null);
    }

    protected override void WriteLogExtended()
    {
      Logger.LogDebug(false, "{0:l} ID: 0x{1:X4}", GetType().Name, ID);
    }
  }
}