using ICSP.Constants;
using ICSP.Logging;

namespace ICSP.Manager.ConnectionManager
{
  /// <summary>
  /// This message is generated by the master or device to confirm receipt of a message sent.
  /// The MessageID field must match the original message's MessageID and the Response bit should be set.
  /// </summary>
  [MsgCmd(ConnectionManagerCmd.BlinkMessage)]
  public class MsgCmdBlinkMessage : ICSPMsg
  {
    public const int MsgCmd = ConnectionManagerCmd.BlinkMessage;

    protected MsgCmdBlinkMessage()
    {
    }

    public MsgCmdBlinkMessage(ICSPMsgData msg) : base(msg)
    {
    }

    public static ICSPMsg CreateRequest(AmxDevice dest, AmxDevice source)
    {
      var lRequest = new MsgCmdBlinkMessage();

      return lRequest.Serialize(dest, source, MsgCmd, null);
    }

    public override void WriteLog(bool last)
    {
      Logger.LogDebug(false, "{0}: Source={1}", GetType().Name, Source);
    }
  }
}
