//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSP.Control.Properties
{
  using System;

  /// <summary>
  ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
  /// </summary>
  // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
  // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
  // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
  // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if(object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSP.Control.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Exit
    {
      get
      {
        object obj = ResourceManager.GetObject("Exit", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FileTransferWorkaround
    {
      get
      {
        object obj = ResourceManager.GetObject("FileTransferWorkaround", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Info
    {
      get
      {
        object obj = ResourceManager.GetObject("Info", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die /*
    ///__          __  _      _____            _             _
    ///\ \        / / | |    / ____|          | |           | |
    /// \ \  /\  / /__| |__ | |     ___  _ __ | |_ _ __ ___ | |
    ///  \ \/  \/ / _ \ &apos;_ \| |    / _ \| &apos;_ \| __| &apos;__/ _ \| |
    ///   \  /\  /  __/ |_) | |___| (_) | | | | |_| | | (_) | |
    ///    \/  \/ \___|_.__/ \_____\___/|_| |_|\__|_|  \___/|_|
    ///
    ///@Description: Global Configuration
    ///*/
    ///
    ///// Config
    ///// ==============================================================================================
    ///var _we [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
    /// </summary>
    internal static string Js_Config
    {
      get
      {
        return ResourceManager.GetString("Js_Config", resourceCulture);
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Misc
    {
      get
      {
        object obj = ResourceManager.GetObject("Misc", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxControlDevice
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxControlDevice", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxDeviceAddressing
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxDeviceAddressing", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxDeviceNotifications
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxDeviceNotifications", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxEmulateCustomEvent
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxEmulateCustomEvent", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxEmulateDevice
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxEmulateDevice", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxInternalDiagnosticsMessages
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxInternalDiagnosticsMessages", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxNetworkAddresses
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxNetworkAddresses", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxNetworkDeviceAddress
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxNetworkDeviceAddress", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NetLinxUrlListing
    {
      get
      {
        object obj = ResourceManager.GetObject("NetLinxUrlListing", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OpenFolder
    {
      get
      {
        object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
    ///&lt;root&gt;
    ///    &lt;fontList&gt;
    ///        &lt;font number=&quot;1&quot;&gt;
    ///            &lt;file&gt;cour.ttf&lt;/file&gt;
    ///            &lt;name&gt;Courier New&lt;/name&gt;
    ///            &lt;subFamily&gt;Regular&lt;/subFamily&gt;
    ///            &lt;fullName&gt;Courier New&lt;/fullName&gt;
    ///            &lt;size&gt;9&lt;/size&gt;
    ///            &lt;usageCount&gt;4012&lt;/usageCount&gt;
    ///        &lt;/font&gt;
    ///        &lt;font number=&quot;2&quot;&gt;
    ///            &lt;file&gt;cour.ttf&lt;/file&gt;
    ///            &lt;name&gt;Courier New&lt;/name&gt;
    ///            &lt;subFamily&gt;Regular&lt;/subFamily&gt;
    ///            &lt;fullName&gt;Courier New&lt;/fullName&gt;
    ///            &lt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
    /// </summary>
    internal static string SysFonts
    {
      get
      {
        return ResourceManager.GetString("SysFonts", resourceCulture);
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TpDesignConnect
    {
      get
      {
        object obj = ResourceManager.GetObject("TpDesignConnect", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TpDesignDisconnect
    {
      get
      {
        object obj = ResourceManager.GetObject("TpDesignDisconnect", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TpDesignReceiveFromPanel
    {
      get
      {
        object obj = ResourceManager.GetObject("TpDesignReceiveFromPanel", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TpDesignSendToPanel
    {
      get
      {
        object obj = ResourceManager.GetObject("TpDesignSendToPanel", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
  }
}
