//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSP.Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.16.101")]
        public string AmxHost {
            get {
                return ((string)(this["AmxHost"]));
            }
            set {
                this["AmxHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1319")]
        public int AmxPort {
            get {
                return ((int)(this["AmxPort"]));
            }
            set {
                this["AmxPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public ushort PhysicalDeviceNumber {
            get {
                return ((ushort)(this["PhysicalDeviceNumber"]));
            }
            set {
                this["PhysicalDeviceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public ushort PhysicalDevicePortCount {
            get {
                return ((ushort)(this["PhysicalDevicePortCount"]));
            }
            set {
                this["PhysicalDevicePortCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PhysicalDeviceAutoCreate {
            get {
                return ((bool)(this["PhysicalDeviceAutoCreate"]));
            }
            set {
                this["PhysicalDeviceAutoCreate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1.00.00")]
        public string PhysicalDeviceVersion {
            get {
                return ((string)(this["PhysicalDeviceVersion"]));
            }
            set {
                this["PhysicalDeviceVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICSP Window")]
        public string PhysicalDeviceName {
            get {
                return ((string)(this["PhysicalDeviceName"]));
            }
            set {
                this["PhysicalDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICSP Manufacturer")]
        public string PhysicalDeviceManufacturer {
            get {
                return ((string)(this["PhysicalDeviceManufacturer"]));
            }
            set {
                this["PhysicalDeviceManufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000000000000000")]
        public string PhysicalDeviceSerialNumber {
            get {
                return ((string)(this["PhysicalDeviceSerialNumber"]));
            }
            set {
                this["PhysicalDeviceSerialNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ushort PhysicalDeviceManufactureId {
            get {
                return ((ushort)(this["PhysicalDeviceManufactureId"]));
            }
            set {
                this["PhysicalDeviceManufactureId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("517")]
        public ushort PhysicalDeviceDeviceId {
            get {
                return ((ushort)(this["PhysicalDeviceDeviceId"]));
            }
            set {
                this["PhysicalDeviceDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G5 MT-1002")]
        public string PhysicalDeviceDeviceType {
            get {
                return ((string)(this["PhysicalDeviceDeviceType"]));
            }
            set {
                this["PhysicalDeviceDeviceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PhysicalDeviceUseCustomDeviceId {
            get {
                return ((bool)(this["PhysicalDeviceUseCustomDeviceId"]));
            }
            set {
                this["PhysicalDeviceUseCustomDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ushort PhysicalDeviceCustomDeviceId {
            get {
                return ((ushort)(this["PhysicalDeviceCustomDeviceId"]));
            }
            set {
                this["PhysicalDeviceCustomDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ushort PhysicalDeviceFirmwareId {
            get {
                return ((ushort)(this["PhysicalDeviceFirmwareId"]));
            }
            set {
                this["PhysicalDeviceFirmwareId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSendText {
            get {
                return ((string)(this["LastSendText"]));
            }
            set {
                this["LastSendText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verbose")]
        public global::Serilog.Events.LogEventLevel LogLevel {
            get {
                return ((global::Serilog.Events.LogEventLevel)(this["LogLevel"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Panel")]
        public string FileTransferPanelDirectory {
            get {
                return ((string)(this["FileTransferPanelDirectory"]));
            }
            set {
                this["FileTransferPanelDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileTransferCreateJson {
            get {
                return ((bool)(this["FileTransferCreateJson"]));
            }
            set {
                this["FileTransferCreateJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("project.json")]
        public string FileTransferFileNameJson {
            get {
                return ((string)(this["FileTransferFileNameJson"]));
            }
            set {
                this["FileTransferFileNameJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileTransferCreateJs {
            get {
                return ((bool)(this["FileTransferCreateJs"]));
            }
            set {
                this["FileTransferCreateJs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("project.js")]
        public string FileTransferFileNameJs {
            get {
                return ((string)(this["FileTransferFileNameJs"]));
            }
            set {
                this["FileTransferFileNameJs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Proj")]
        public string FileTransferVariableNameJs {
            get {
                return ((string)(this["FileTransferVariableNameJs"]));
            }
            set {
                this["FileTransferVariableNameJs"] = value;
            }
        }
    }
}
