//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSP.WebProxy.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSP.WebProxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;0&quot;: {
        ///    &quot;name&quot;: &quot;VeryLightRed&quot;,
        ///    &quot;color&quot;: &quot;#FF0000FF&quot;
        ///  },
        ///  &quot;1&quot;: {
        ///    &quot;name&quot;: &quot;LightRed&quot;,
        ///    &quot;color&quot;: &quot;#DF0000FF&quot;
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;name&quot;: &quot;Red&quot;,
        ///    &quot;color&quot;: &quot;#BF0000FF&quot;
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;name&quot;: &quot;MediumRed&quot;,
        ///    &quot;color&quot;: &quot;#9F0000FF&quot;
        ///  },
        ///  &quot;4&quot;: {
        ///    &quot;name&quot;: &quot;DarkRed&quot;,
        ///    &quot;color&quot;: &quot;#7F0000FF&quot;
        ///  },
        ///  &quot;5&quot;: {
        ///    &quot;name&quot;: &quot;VeryDarkRed&quot;,
        ///    &quot;color&quot;: &quot;#5F0000FF&quot;
        ///  },
        ///  &quot;6&quot;: {
        ///    &quot;name&quot;: &quot;VeryLightOrange&quot;,
        ///    &quot;color&quot;: &quot;#FF8000FF&quot;
        ///  },
        ///  &quot;7&quot;: {
        ///    &quot;name&quot;: &quot;LightOrange&quot;,
        ///    &quot;color&quot;: &quot;#DF7000FF&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DefaultPalette {
            get {
                return ResourceManager.GetString("DefaultPalette", resourceCulture);
            }
        }
    }
}
