//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSP.WebProxy.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSP.WebProxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;0&quot;: {
        ///    &quot;name&quot;: &quot;VeryLightRed&quot;,
        ///    &quot;color&quot;: &quot;#FF0000FF&quot;
        ///  },
        ///  &quot;1&quot;: {
        ///    &quot;name&quot;: &quot;LightRed&quot;,
        ///    &quot;color&quot;: &quot;#DF0000FF&quot;
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;name&quot;: &quot;Red&quot;,
        ///    &quot;color&quot;: &quot;#BF0000FF&quot;
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;name&quot;: &quot;MediumRed&quot;,
        ///    &quot;color&quot;: &quot;#9F0000FF&quot;
        ///  },
        ///  &quot;4&quot;: {
        ///    &quot;name&quot;: &quot;DarkRed&quot;,
        ///    &quot;color&quot;: &quot;#7F0000FF&quot;
        ///  },
        ///  &quot;5&quot;: {
        ///    &quot;name&quot;: &quot;VeryDarkRed&quot;,
        ///    &quot;color&quot;: &quot;#5F0000FF&quot;
        ///  },
        ///  &quot;6&quot;: {
        ///    &quot;name&quot;: &quot;VeryLightOrange&quot;,
        ///    &quot;color&quot;: &quot;#FF8000FF&quot;
        ///  },
        ///  &quot;7&quot;: {
        ///    &quot;name&quot;: &quot;LightOrange&quot;,
        ///    &quot;color&quot;: &quot;#DF7000FF&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DefaultPalette {
            get {
                return ResourceManager.GetString("DefaultPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///  &lt;title&gt;Error | ICSP.WebProxy&lt;/title&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///    html, body, div, h1, h2, h3, h4, h5, h6, p, a, form, fieldset, select, input, ul, li, table, td, th, img {
        ///      padding: 0px;
        ///      margin: 0px;
        ///    }
        ///
        ///    img {
        ///      border: none;
        ///    }
        ///
        ///    h1 {
        ///      padding: 0;
        ///      font-size: 46px;
        ///      font-weight: normal;
        ///      line-height: 60px;
        ///      color: #000;
        ///      pad [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Error_404_html {
            get {
                return ResourceManager.GetString("Error_404_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Error_404_jpg {
            get {
                object obj = ResourceManager.GetObject("Error_404_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Error_404_V01_freak {
            get {
                object obj = ResourceManager.GetObject("Error_404_V01_freak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Error_404_V02_notfound {
            get {
                object obj = ResourceManager.GetObject("Error_404_V02_notfound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Error_404_V03_monster {
            get {
                object obj = ResourceManager.GetObject("Error_404_V03_monster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Error_404_V04_pixar {
            get {
                object obj = ResourceManager.GetObject("Error_404_V04_pixar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ﻿
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;title&gt;{title}&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;pragma&quot; content=&quot;no-cache, no-store&quot;&gt;
        ///  &lt;meta http-equiv=&quot;expires&quot; content=&quot;0&quot;&gt;
        ///  &lt;meta http-equiv=&quot;cache-control&quot; content=&quot;no-cache, no-store&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=0&quot;&gt;
        ///  &lt;link rel=&quot;apple-touch-icon&quot; sizes=&quot;57x57&quot; href=&quot;AMXPanel/images/icon/apple-icon-57x57.png&quot;&gt;
        ///  &lt;link re [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///  &lt;title&gt;Status 4001 | ICSP.WebProxy&lt;/title&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///    html, body, div, h1, h2, h3, h4, h5, h6, p, a, form, fieldset, select, input, ul, li, table, td, th, img {
        ///      padding: 0px;
        ///      margin: 0px;
        ///    }
        ///
        ///    img {
        ///      border: none;
        ///    }
        ///
        ///    h1 {
        ///      padding: 0;
        ///      font-size: 46px;
        ///      font-weight: normal;
        ///      line-height: 60px;
        ///      color: #000;
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Status_4001 {
            get {
                return ResourceManager.GetString("Status_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;1&quot;: {
        ///    &quot;file&quot;: &quot;cour.ttf&quot;,
        ///    &quot;name&quot;: &quot;Courier New&quot;,
        ///    &quot;subfamilyName&quot;: &quot;Regular&quot;,
        ///    &quot;fullName&quot;: &quot;Courier New&quot;,
        ///    &quot;size&quot;: &quot;9&quot;,
        ///    &quot;usageCount&quot;: &quot;4012&quot;
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;file&quot;: &quot;cour.ttf&quot;,
        ///    &quot;name&quot;: &quot;Courier New&quot;,
        ///    &quot;subfamilyName&quot;: &quot;Regular&quot;,
        ///    &quot;fullName&quot;: &quot;Courier New&quot;,
        ///    &quot;size&quot;: &quot;12&quot;,
        ///    &quot;usageCount&quot;: &quot;4001&quot;
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;file&quot;: &quot;cour.ttf&quot;,
        ///    &quot;name&quot;: &quot;Courier New&quot;,
        ///    &quot;subfamilyName&quot;: &quot;Regular&quot;,
        ///    &quot;fullName&quot;: &quot;Courier New&quot;,
        ///    &quot;size&quot;: &quot;18&quot;,
        ///    &quot;usageCount&quot;: &quot;4001&quot;
        ///  } [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SystemFonts {
            get {
                return ResourceManager.GetString("SystemFonts", resourceCulture);
            }
        }
    }
}
