namespace ICSP.Constants
{
  /// <summary>
  ///  Connection Manager Messages (Table B)
  /// </summary>
  public static class ConnectionManagerCmd
  {
    /// <summary>
    ///  Requests a ping response from the destination device.
    /// </summary>
    public const int PingRequest = 0x0501;

    /// <summary>
    /// Reply to the Ping Request.
    /// The master uses the response to confirm that the device is active in the system.
    /// </summary>
    public const int PingResponse = 0x0581;

    /// <summary>
    /// Periodically broadcast to all devices.
    /// Includes LED blink and other information.
    /// </summary>
    public const int BlinkMessage = 0x0502;

    /// <summary>
    /// Requests a Blink message.
    /// Intended to be generated by one master to another.
    /// </summary>
    public const int BlinkRequest = 0x0582;

    /// <summary>
    /// Assigned address response.
    /// </summary>
    public const int DynamicDeviceAddressResponse = 0x0503;

    /// <summary>
    /// Request a dynamic address. Use the Newbee flag.
    /// </summary>
    public const int DynamicDeviceAddressRequest = 0x0583;

    /// <summary>
    /// Requests that strings from the specified device get sent to another specified device.
    /// </summary>
    public const int PassThroughRequests = 0x0584;

    /// <summary>
    /// Requests notification of specific messages from a device.
    /// </summary>
    public const int NotificationRequest = 0x0507;
  }
}